# Generated by Django 3.2.19 on 2025-04-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250426_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Price',
            new_name='price',
        ),
    ]
